# Generated by Django 3.1.5 on 2021-02-16 18:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Kategorija',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ime', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Skladiste',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naziv', models.CharField(blank=True, max_length=50, null=True)),
                ('kolicina', models.IntegerField(blank=True, default=0, null=True)),
                ('primljena_kolicina', models.IntegerField(blank=True, default=0, null=True)),
                ('zaprimio', models.CharField(blank=True, max_length=50, null=True)),
                ('izdana_kolicina', models.IntegerField(blank=True, default=0, null=True)),
                ('izdao', models.CharField(blank=True, max_length=50, null=True)),
                ('izdano_na', models.CharField(blank=True, max_length=50, null=True)),
                ('kreirao', models.CharField(blank=True, max_length=50, null=True)),
                ('zaduzena_kolicina', models.IntegerField(blank=True, default=0, null=True)),
                ('reorder_level', models.IntegerField(blank=True, default=0, null=True)),
                ('zadnje_osvjezeno', models.DateField(auto_now=True)),
                ('export_to_CSV', models.BooleanField(default=False)),
                ('kategorija', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Skladiste.kategorija')),
            ],
        ),
        migrations.CreateModel(
            name='Zaduzenje',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datum_zaduzivanja', models.DateTimeField(auto_now=True)),
                ('naziv', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Skladiste.skladiste')),
                ('zaduzeno_na', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SkladisteHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naziv', models.CharField(blank=True, max_length=50, null=True)),
                ('kolicina', models.IntegerField(blank=True, default=0, null=True)),
                ('primljena_kolicina', models.IntegerField(blank=True, default=0, null=True)),
                ('zaprimio', models.CharField(blank=True, max_length=50, null=True)),
                ('izdana_kolicina', models.IntegerField(blank=True, default=0, null=True)),
                ('izdao', models.CharField(blank=True, max_length=50, null=True)),
                ('izdano_na', models.CharField(blank=True, max_length=50, null=True)),
                ('kreirao', models.CharField(blank=True, max_length=50, null=True)),
                ('reorder_level', models.IntegerField(blank=True, default=0, null=True)),
                ('zadnje_osvjezeno', models.DateField(null=True)),
                ('kategorija', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Skladiste.kategorija')),
            ],
        ),
        migrations.AddField(
            model_name='skladiste',
            name='zaduzio',
            field=models.ManyToManyField(through='Skladiste.Zaduzenje', to=settings.AUTH_USER_MODEL),
        ),
    ]
