# Generated by Django 3.1.5 on 2021-01-28 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AlatiRucni',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naziv', models.CharField(max_length=50)),
                ('zaduzeno', models.BooleanField()),
                ('zaduzio', models.CharField(max_length=50)),
                ('zad_datum', models.DateField()),
                ('razduzeno', models.BooleanField()),
                ('razd_datum', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='AlatiStrojni',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naziv', models.CharField(max_length=50)),
                ('zaduzeno', models.BooleanField()),
                ('zaduzio', models.CharField(max_length=50)),
                ('zad_datum', models.DateField()),
                ('razduzeno', models.BooleanField()),
                ('razd_datum', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Instrument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naziv', models.CharField(max_length=50)),
                ('zaduzeno', models.BooleanField()),
                ('zaduzio', models.CharField(max_length=50)),
                ('zad_datum', models.DateField()),
                ('razduzeno', models.BooleanField()),
                ('razd_datum', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Oprema',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(max_length=50)),
                ('tip', models.CharField(max_length=50)),
                ('proizvodac', models.CharField(max_length=50)),
                ('model', models.CharField(max_length=50)),
                ('serial', models.CharField(max_length=50)),
                ('zaduzeno', models.BooleanField()),
                ('zaduzio', models.CharField(max_length=50)),
                ('zad_datum', models.DateField()),
                ('razduzeno', models.BooleanField()),
                ('razd_datum', models.DateField()),
            ],
        ),
    ]
