# Generated by Django 3.1.5 on 2021-01-29 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Skladiste', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skladiste',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kategorija', models.CharField(blank=True, max_length=50, null=True)),
                ('naziv', models.CharField(blank=True, max_length=50, null=True)),
                ('kolicina', models.IntegerField(blank=True, default=0, null=True)),
                ('primljena_kolicina', models.IntegerField(blank=True, default=0, null=True)),
                ('zaprimio', models.CharField(blank=True, max_length=50, null=True)),
                ('izdana_kolicina', models.IntegerField(blank=True, default=0, null=True)),
                ('izdao', models.CharField(blank=True, max_length=50, null=True)),
                ('izdano_na', models.CharField(blank=True, max_length=50, null=True)),
                ('kreirao', models.CharField(blank=True, max_length=50, null=True)),
                ('reorder_level', models.IntegerField(blank=True, default=0, null=True)),
                ('zadnje_osvjezeno', models.DateField(auto_now=True)),
            ],
        ),
        migrations.DeleteModel(
            name='AlatiRucni',
        ),
        migrations.DeleteModel(
            name='AlatiStrojni',
        ),
        migrations.DeleteModel(
            name='Instrument',
        ),
        migrations.DeleteModel(
            name='Oprema',
        ),
    ]
