# Generated by Django 3.1.5 on 2021-02-16 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Skladiste', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='zaduzenje',
            name='datum_zaduzivanja',
        ),
        migrations.AddField(
            model_name='skladiste',
            name='datum_zaduzivanja',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
