# Generated by Django 3.1.5 on 2021-02-17 13:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Skladiste', '0002_auto_20210216_2248'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipKabela',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tip', models.CharField(blank=True, max_length=50, null=True, verbose_name='Tip kabela')),
            ],
        ),
        migrations.AlterField(
            model_name='skladiste',
            name='kolicina',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.CreateModel(
            name='Materijal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inv_broj', models.PositiveIntegerField(unique=True, verbose_name='Inventurni broj')),
                ('naziv', models.CharField(max_length=50, verbose_name='Naziv')),
                ('kolicina', models.PositiveIntegerField(verbose_name='Količina')),
                ('zaprimljena_kolicina', models.PositiveIntegerField(verbose_name='Zaprimljena količina')),
                ('izdana_kolicina', models.PositiveIntegerField(verbose_name='Izdana količina')),
                ('radnja', models.CharField(max_length=50, verbose_name='Radnja')),
                ('reorder_level', models.IntegerField(blank=True, default=0, null=True)),
                ('export_to_CSV', models.BooleanField(default=False)),
                ('izdano_na', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Izdaj na')),
                ('izdao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='korisnik', to=settings.AUTH_USER_MODEL)),
                ('zaprimio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', to=settings.AUTH_USER_MODEL, verbose_name='Zaprimio')),
            ],
        ),
        migrations.CreateModel(
            name='KabelUtp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inv_broj', models.PositiveIntegerField(unique=True, verbose_name='Inventurni broj')),
                ('naziv', models.CharField(max_length=50, verbose_name='Naziv')),
                ('proizvodjac', models.CharField(max_length=50, verbose_name='Proizvođač')),
                ('vlasnik', models.CharField(max_length=50, verbose_name='Vlasnik')),
                ('tip_kabela', models.CharField(max_length=50, verbose_name='Tip kabela')),
                ('broj_pari', models.PositiveIntegerField(verbose_name='Broj parica')),
                ('ukupna_metraza', models.PositiveIntegerField(verbose_name='Ukupna metraža')),
                ('izdana_metraza', models.PositiveIntegerField(verbose_name='Izdano metara')),
                ('preostala_metraza', models.PositiveIntegerField()),
                ('reorder_level', models.IntegerField(blank=True, default=0, null=True)),
                ('export_to_CSV', models.BooleanField(default=False)),
                ('izdano_na', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Izdaj na')),
            ],
        ),
        migrations.CreateModel(
            name='KabelOptika',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inv_broj', models.PositiveIntegerField(unique=True, verbose_name='Inventurni broj')),
                ('naziv', models.CharField(max_length=50, verbose_name='Naziv')),
                ('proizvodjac', models.CharField(max_length=50, verbose_name='Proizvođač')),
                ('vlasnik', models.CharField(max_length=50, verbose_name='Vlasnik')),
                ('tip_kabela', models.CharField(max_length=50, verbose_name='Tip kabela')),
                ('broj_niti', models.PositiveIntegerField(verbose_name='Broj niti')),
                ('ukupna_metraza', models.PositiveIntegerField(verbose_name='Ukupna metraža')),
                ('izdana_metraza', models.PositiveIntegerField(verbose_name='Izdano metara')),
                ('preostala_metraza', models.PositiveIntegerField()),
                ('reorder_level', models.IntegerField(blank=True, default=0, null=True)),
                ('export_to_CSV', models.BooleanField(default=False)),
                ('izdano_na', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Izdaj na')),
            ],
        ),
        migrations.CreateModel(
            name='KabelBakar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inv_broj', models.PositiveIntegerField(unique=True, verbose_name='Inventurni broj')),
                ('naziv', models.CharField(max_length=50, verbose_name='Naziv')),
                ('proizvodjac', models.CharField(max_length=50, verbose_name='Proizvođač')),
                ('vlasnik', models.CharField(max_length=50, verbose_name='Vlasnik')),
                ('tip_kabela', models.CharField(max_length=50, verbose_name='Tip kabela')),
                ('broj_pari', models.PositiveIntegerField(verbose_name='Broj parica')),
                ('ukupna_metraza', models.PositiveIntegerField(verbose_name='Ukupna metraža')),
                ('izdana_metraza', models.PositiveIntegerField(verbose_name='Izdano metara')),
                ('preostala_metraza', models.PositiveIntegerField()),
                ('reorder_level', models.IntegerField(blank=True, default=0, null=True)),
                ('export_to_CSV', models.BooleanField(default=False)),
                ('izdano_na', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Izdaj na')),
            ],
        ),
        migrations.CreateModel(
            name='Alat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inv_broj', models.PositiveIntegerField(unique=True, verbose_name='Inventurni broj')),
                ('naziv', models.CharField(max_length=50, verbose_name='Naziv')),
                ('proizvodjac', models.CharField(max_length=50, verbose_name='Proizvođač')),
                ('sr_broj', models.CharField(max_length=50, verbose_name='Serijski broj')),
                ('kreirao', models.CharField(blank=True, max_length=50, null=True)),
                ('datum_zaduzivanja', models.DateField(auto_now=True, verbose_name='Zaduženo dana')),
                ('zadnje_osvjezeno', models.DateField(auto_now=True, verbose_name='Posljednje ažuriranje')),
                ('export_to_CSV', models.BooleanField(default=False)),
                ('zaduzio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Zaduži na')),
            ],
        ),
    ]
