# Generated by Django 3.1.5 on 2021-01-29 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Skladiste', '0002_auto_20210129_1434'),
    ]

    operations = [
        migrations.AddField(
            model_name='skladiste',
            name='export_to_CSV',
            field=models.BooleanField(default=False),
        ),
    ]
