# Generated by Django 3.1.5 on 2021-02-17 13:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Skladiste', '0003_auto_20210217_1419'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kabelbakar',
            name='broj_pari',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Broj parica'),
        ),
        migrations.AlterField(
            model_name='kabelbakar',
            name='inv_broj',
            field=models.PositiveIntegerField(blank=True, null=True, unique=True, verbose_name='Inventurni broj'),
        ),
        migrations.AlterField(
            model_name='kabelbakar',
            name='izdana_metraza',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Izdano metara'),
        ),
        migrations.AlterField(
            model_name='kabelbakar',
            name='izdano_na',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Izdaj na'),
        ),
        migrations.AlterField(
            model_name='kabelbakar',
            name='naziv',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Naziv'),
        ),
        migrations.AlterField(
            model_name='kabelbakar',
            name='preostala_metraza',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='kabelbakar',
            name='proizvodjac',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Proizvođač'),
        ),
        migrations.AlterField(
            model_name='kabelbakar',
            name='tip_kabela',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Tip kabela'),
        ),
        migrations.AlterField(
            model_name='kabelbakar',
            name='ukupna_metraza',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Ukupna metraža'),
        ),
        migrations.AlterField(
            model_name='kabelbakar',
            name='vlasnik',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Vlasnik'),
        ),
        migrations.AlterField(
            model_name='kabeloptika',
            name='broj_niti',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Broj niti'),
        ),
        migrations.AlterField(
            model_name='kabeloptika',
            name='inv_broj',
            field=models.PositiveIntegerField(blank=True, null=True, unique=True, verbose_name='Inventurni broj'),
        ),
        migrations.AlterField(
            model_name='kabeloptika',
            name='izdana_metraza',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Izdano metara'),
        ),
        migrations.AlterField(
            model_name='kabeloptika',
            name='izdano_na',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Izdaj na'),
        ),
        migrations.AlterField(
            model_name='kabeloptika',
            name='naziv',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Naziv'),
        ),
        migrations.AlterField(
            model_name='kabeloptika',
            name='preostala_metraza',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='kabeloptika',
            name='proizvodjac',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Proizvođač'),
        ),
        migrations.AlterField(
            model_name='kabeloptika',
            name='tip_kabela',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Tip kabela'),
        ),
        migrations.AlterField(
            model_name='kabeloptika',
            name='ukupna_metraza',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Ukupna metraža'),
        ),
        migrations.AlterField(
            model_name='kabeloptika',
            name='vlasnik',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Vlasnik'),
        ),
    ]
