# Generated by Django 3.1.5 on 2021-01-31 11:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Skladiste', '0003_skladiste_export_to_csv'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kategorija',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ime', models.CharField(blank=True, choices=[('Alat ručni', 'Alat ručni'), ('Alat strojni', 'Alat strojni'), ('IT oprema', 'IT oprema'), ('Materijal', 'Materijal')], max_length=50, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='skladiste',
            name='kategorija',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Skladiste.kategorija'),
            preserve_default=False,
        ),
    ]
