# Generated by Django 3.1.5 on 2021-02-17 14:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Skladiste', '0004_auto_20210217_1436'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kabeloptika',
            name='broj_niti',
            field=models.PositiveIntegerField(default=1, verbose_name='Broj niti'),
        ),
        migrations.AlterField(
            model_name='kabeloptika',
            name='naziv',
            field=models.CharField(default=1, max_length=50, verbose_name='Naziv'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='kabeloptika',
            name='tip_kabela',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Skladiste.tipkabela', verbose_name='Tip kabela'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='kabeloptika',
            name='ukupna_metraza',
            field=models.PositiveIntegerField(default=0, verbose_name='Ukupna metraža'),
        ),
        migrations.AlterField(
            model_name='kabeloptika',
            name='vlasnik',
            field=models.CharField(default=1, max_length=50, verbose_name='Vlasnik'),
            preserve_default=False,
        ),
    ]
