# Generated by Django 3.1.5 on 2021-02-14 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Skladiste', '0004_auto_20210131_1216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kategorija',
            name='ime',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
