# Generated by Django 3.1.5 on 2021-02-14 17:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Skladiste', '0005_auto_20210214_1341'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skladiste',
            name='kategorija',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Skladiste.kategorija'),
        ),
        migrations.CreateModel(
            name='SkladisteHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naziv', models.CharField(blank=True, max_length=50, null=True)),
                ('kolicina', models.IntegerField(blank=True, default=0, null=True)),
                ('primljena_kolicina', models.IntegerField(blank=True, default=0, null=True)),
                ('zaprimio', models.CharField(blank=True, max_length=50, null=True)),
                ('izdana_kolicina', models.IntegerField(blank=True, default=0, null=True)),
                ('izdao', models.CharField(blank=True, max_length=50, null=True)),
                ('izdano_na', models.CharField(blank=True, max_length=50, null=True)),
                ('kreirao', models.CharField(blank=True, max_length=50, null=True)),
                ('reorder_level', models.IntegerField(blank=True, default=0, null=True)),
                ('zadnje_osvjezeno', models.DateField()),
                ('kategorija', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Skladiste.kategorija')),
            ],
        ),
    ]
