# Generated by Django 3.1.5 on 2021-02-17 14:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Skladiste', '0005_auto_20210217_1532'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kabelbakar',
            name='tip_kabela',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Skladiste.tipkabela', verbose_name='Tip kabela'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='kabelutp',
            name='tip_kabela',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Skladiste.tipkabela', verbose_name='Tip kabela'),
        ),
    ]
