# Generated by Django 3.1.5 on 2021-02-17 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Skladiste', '0006_auto_20210217_1536'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kabelbakar',
            name='broj_pari',
            field=models.PositiveIntegerField(default=1, verbose_name='Broj parica'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='kabelbakar',
            name='inv_broj',
            field=models.PositiveIntegerField(default=1, unique=True, verbose_name='Inventurni broj'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='kabelbakar',
            name='naziv',
            field=models.CharField(default=1, max_length=50, verbose_name='Naziv'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='kabelbakar',
            name='ukupna_metraza',
            field=models.PositiveIntegerField(default=1, verbose_name='Ukupna metraža'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='kabelbakar',
            name='vlasnik',
            field=models.CharField(default=2, max_length=50, verbose_name='Vlasnik'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='kabelutp',
            name='izdana_metraza',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Izdano metara'),
        ),
        migrations.AlterField(
            model_name='kabelutp',
            name='naziv',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Naziv'),
        ),
        migrations.AlterField(
            model_name='kabelutp',
            name='preostala_metraza',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='kabelutp',
            name='proizvodjac',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Proizvođač'),
        ),
    ]
