# Generated by Django 3.1.5 on 2021-02-17 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Skladiste', '0007_auto_20210217_1543'),
    ]

    operations = [
        migrations.AddField(
            model_name='kabelbakar',
            name='radnja',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Radnja'),
        ),
        migrations.AddField(
            model_name='kabeloptika',
            name='radnja',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Radnja'),
        ),
        migrations.AddField(
            model_name='kabelutp',
            name='radnja',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Radnja'),
        ),
        migrations.AlterField(
            model_name='kabelutp',
            name='naziv',
            field=models.CharField(default=1, max_length=50, verbose_name='Naziv'),
            preserve_default=False,
        ),
    ]
