# Generated by Django 3.1.5 on 2021-02-14 22:08

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Skladiste', '0007_auto_20210214_1832'),
    ]

    operations = [
        migrations.AddField(
            model_name='skladiste',
            name='zaduzio',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='skladistehistory',
            name='zaduzio',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
