# Generated by Django 3.1.5 on 2021-02-17 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Skladiste', '0008_auto_20210217_1549'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kabelutp',
            name='broj_pari',
        ),
    ]
