# Generated by Django 3.1.5 on 2021-02-17 14:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Skladiste', '0009_remove_kabelutp_broj_pari'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kabelutp',
            name='izdano_na',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Izdaj na'),
        ),
    ]
