# Generated by Django 3.1.5 on 2021-02-15 18:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Skladiste', '0010_auto_20210215_1453'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skladiste',
            name='zaduzio',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='artikl_zaduzio', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='skladistehistory',
            name='zaduzio',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='skladisteh_zaduzio', to=settings.AUTH_USER_MODEL),
        ),
    ]
