# Generated by Django 3.1.5 on 2021-02-17 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Skladiste', '0010_auto_20210217_1557'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materijal',
            name='izdao',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
