# Generated by Django 3.1.5 on 2021-02-15 19:08

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Skladiste', '0011_auto_20210215_1934'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skladiste',
            name='zaduzio',
        ),
        migrations.AddField(
            model_name='skladiste',
            name='zaduzio',
            field=models.ManyToManyField(blank=True, related_name='artikl_zaduzio', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='skladistehistory',
            name='zaduzio',
        ),
        migrations.AddField(
            model_name='skladistehistory',
            name='zaduzio',
            field=models.ManyToManyField(blank=True, related_name='skladisteh_zaduzio', to=settings.AUTH_USER_MODEL),
        ),
    ]
