# Generated by Django 3.1.5 on 2021-02-17 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Skladiste', '0011_auto_20210217_2322'),
    ]

    operations = [
        migrations.AddField(
            model_name='kabeloptika',
            name='izdao',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
