# Generated by Django 3.1.5 on 2021-02-15 22:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Skladiste', '0012_auto_20210215_2008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skladiste',
            name='zaduzio',
            field=models.ManyToManyField(blank=True, related_name='users', to=settings.AUTH_USER_MODEL),
        ),
    ]
