# Generated by Django 3.1.5 on 2021-02-17 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Skladiste', '0012_kabeloptika_izdao'),
    ]

    operations = [
        migrations.AddField(
            model_name='kabeloptika',
            name='kreirao',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
