# Generated by Django 3.1.5 on 2021-02-20 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Skladiste', '0013_kabeloptika_kreirao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kabeloptika',
            name='inv_broj',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Inventurni broj'),
        ),
        migrations.AlterField(
            model_name='kabeloptika',
            name='naziv',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Naziv'),
        ),
    ]
