# Generated by Django 3.1.5 on 2021-02-20 22:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Skladiste', '0014_auto_20210220_2117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kabeloptika',
            name='tip_kabela',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Skladiste.tipkabela', verbose_name='Tip kabela'),
        ),
        migrations.AlterField(
            model_name='kabeloptika',
            name='vlasnik',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Vlasnik'),
        ),
        migrations.AlterField(
            model_name='materijal',
            name='inv_broj',
            field=models.PositiveIntegerField(default=0, verbose_name='Inventurni broj'),
        ),
        migrations.AlterField(
            model_name='tipkabela',
            name='tip',
            field=models.CharField(default=1, max_length=50, verbose_name='Tip kabela'),
            preserve_default=False,
        ),
    ]
