# Generated by Django 3.1.5 on 2021-02-20 23:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Skladiste', '0016_auto_20210220_2359'),
    ]

    operations = [
        migrations.AddField(
            model_name='kabelbakar',
            name='zadnje_osvjezeno',
            field=models.DateField(auto_now=True, verbose_name='Posljednje ažuriranje'),
        ),
        migrations.AddField(
            model_name='kabeloptika',
            name='zadnje_osvjezeno',
            field=models.DateField(auto_now=True, verbose_name='Posljednje ažuriranje'),
        ),
        migrations.AddField(
            model_name='kabelutp',
            name='zadnje_osvjezeno',
            field=models.DateField(auto_now=True, verbose_name='Posljednje ažuriranje'),
        ),
        migrations.CreateModel(
            name='KabelOptikaHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inv_broj', models.PositiveIntegerField(blank=True, null=True, verbose_name='Inventurni broj')),
                ('naziv', models.CharField(blank=True, max_length=50, null=True, verbose_name='Naziv')),
                ('proizvodjac', models.CharField(blank=True, max_length=50, null=True, verbose_name='Proizvođač')),
                ('vlasnik', models.CharField(blank=True, max_length=50, null=True, verbose_name='Vlasnik')),
                ('broj_niti', models.PositiveIntegerField(default=1, verbose_name='Broj niti')),
                ('metraza', models.PositiveIntegerField(default=0, verbose_name='Ukupna metraža')),
                ('izdana_metraza', models.PositiveIntegerField(blank=True, null=True, verbose_name='Izdano metara')),
                ('izdao', models.CharField(blank=True, max_length=50, null=True)),
                ('kreirao', models.CharField(blank=True, max_length=50, null=True)),
                ('radnja', models.CharField(blank=True, max_length=50, null=True, verbose_name='Radnja')),
                ('reorder_level', models.IntegerField(blank=True, default=0, null=True)),
                ('zadnje_osvjezeno', models.DateField(null=True, verbose_name='Posljednje ažuriranje')),
                ('export_to_CSV', models.BooleanField(default=False)),
                ('izdano_na', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Izdaj na')),
                ('tip_kabela', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Skladiste.tipkabela', verbose_name='Tip kabela')),
            ],
        ),
    ]
