# Generated by Django 3.1.5 on 2021-02-21 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Skladiste', '0018_auto_20210221_0036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kabeloptika',
            name='broj_niti',
            field=models.PositiveIntegerField(blank=True, default=1, null=True, verbose_name='Broj niti'),
        ),
    ]
