# Generated by Django 3.1.5 on 2021-02-23 17:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Skladiste', '0023_auto_20210223_1808'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kabelbakar',
            name='broj_pari',
            field=models.IntegerField(blank=True, null=True, verbose_name='Broj parica'),
        ),
        migrations.AlterField(
            model_name='kabelbakar',
            name='izdana_metraza',
            field=models.IntegerField(blank=True, null=True, verbose_name='Izdano metara'),
        ),
        migrations.AlterField(
            model_name='kabelbakar',
            name='metraza',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Ukupna metraža'),
        ),
        migrations.AlterField(
            model_name='kabelbakar',
            name='naziv',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Naziv'),
        ),
        migrations.AlterField(
            model_name='kabelbakar',
            name='tip_kabela',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Skladiste.tipkabela', verbose_name='Tip kabela'),
        ),
    ]
