# Generated by Django 3.1.5 on 2021-02-23 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Skladiste', '0024_auto_20210223_1821'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kabelbakar',
            name='vlasnik',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Vlasnik'),
        ),
    ]
