# Generated by Django 3.1.5 on 2021-02-23 22:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Skladiste', '0025_auto_20210223_1825'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kabelutp',
            name='inv_broj',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Inventurni broj'),
        ),
        migrations.AlterField(
            model_name='kabelutp',
            name='izdana_metraza',
            field=models.IntegerField(blank=True, null=True, verbose_name='Izdano metara'),
        ),
        migrations.AlterField(
            model_name='kabelutp',
            name='metraza',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Ukupna metraža'),
        ),
        migrations.AlterField(
            model_name='kabelutp',
            name='tip_kabela',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Skladiste.tipkabela', verbose_name='Tip kabela'),
        ),
        migrations.AlterField(
            model_name='kabelutp',
            name='vlasnik',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Vlasnik'),
        ),
        migrations.CreateModel(
            name='KabelUtpHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inv_broj', models.IntegerField(blank=True, default=0, null=True, verbose_name='Inventurni broj')),
                ('naziv', models.CharField(max_length=50, verbose_name='Naziv')),
                ('proizvodjac', models.CharField(blank=True, max_length=50, null=True, verbose_name='Proizvođač')),
                ('vlasnik', models.CharField(blank=True, max_length=50, null=True, verbose_name='Vlasnik')),
                ('metraza', models.IntegerField(blank=True, default=0, null=True, verbose_name='Ukupna metraža')),
                ('izdana_metraza', models.IntegerField(blank=True, null=True, verbose_name='Izdano metara')),
                ('radnja', models.CharField(blank=True, max_length=50, null=True, verbose_name='Radnja')),
                ('reorder_level', models.IntegerField(blank=True, default=0, null=True)),
                ('zadnje_osvjezeno', models.DateField(auto_now=True, verbose_name='Posljednje ažuriranje')),
                ('export_to_CSV', models.BooleanField(default=False)),
                ('izdano_na', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Izdaj na')),
                ('tip_kabela', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Skladiste.tipkabela', verbose_name='Tip kabela')),
            ],
        ),
    ]
