# Generated by Django 3.1.5 on 2021-02-24 16:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Skladiste', '0027_auto_20210223_2357'),
    ]

    operations = [
        migrations.CreateModel(
            name='CijevHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inv_broj', models.IntegerField(blank=True, null=True, verbose_name='Inventurni broj')),
                ('naziv', models.CharField(blank=True, max_length=50, null=True, verbose_name='Naziv')),
                ('proizvodjac', models.CharField(blank=True, max_length=50, null=True, verbose_name='Proizvođač')),
                ('vlasnik', models.CharField(blank=True, max_length=50, null=True, verbose_name='Vlasnik')),
                ('Promjer', models.IntegerField(default=1, verbose_name='Promjer')),
                ('metraza', models.IntegerField(default=0, verbose_name='Ukupna metraža')),
                ('izdana_metraza', models.IntegerField(blank=True, null=True, verbose_name='Izdano metara')),
                ('izdao', models.CharField(blank=True, max_length=50, null=True)),
                ('kreirao', models.CharField(blank=True, max_length=50, null=True)),
                ('radnja', models.CharField(blank=True, max_length=50, null=True, verbose_name='Radnja')),
                ('reorder_level', models.IntegerField(blank=True, default=0, null=True)),
                ('zadnje_osvjezeno', models.DateTimeField(null=True, verbose_name='Posljednje ažuriranje')),
                ('export_to_CSV', models.BooleanField(default=False)),
                ('izdano_na', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Izdaj na')),
                ('vrsta_cijevi', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Skladiste.tipkabela', verbose_name='Vrsta cijevi')),
            ],
        ),
        migrations.CreateModel(
            name='Cijev',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inv_broj', models.IntegerField(blank=True, default=0, null=True, verbose_name='Inventurni broj')),
                ('naziv', models.CharField(blank=True, max_length=50, null=True, verbose_name='Naziv')),
                ('proizvodjac', models.CharField(blank=True, max_length=50, null=True, verbose_name='Proizvođač')),
                ('vlasnik', models.CharField(blank=True, max_length=50, null=True, verbose_name='Vlasnik')),
                ('promjer', models.IntegerField(blank=True, null=True, verbose_name='Promjer')),
                ('metraza', models.IntegerField(blank=True, default=0, null=True, verbose_name='Ukupna metraža')),
                ('izdana_metraza', models.IntegerField(blank=True, null=True, verbose_name='Izdano metara')),
                ('izdao', models.CharField(blank=True, max_length=50, null=True)),
                ('kreirao', models.CharField(blank=True, max_length=50, null=True)),
                ('radnja', models.CharField(blank=True, max_length=50, null=True, verbose_name='Radnja')),
                ('reorder_level', models.IntegerField(blank=True, default=0, null=True)),
                ('zadnje_osvjezeno', models.DateTimeField(auto_now=True, verbose_name='Posljednje ažuriranje')),
                ('export_to_CSV', models.BooleanField(default=False)),
                ('izdano_na', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Izdaj na')),
                ('vrsta_cijevi', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Skladiste.tipkabela', verbose_name='Vrsta cijevi')),
            ],
        ),
    ]
