# Generated by Django 3.1.5 on 2021-02-24 21:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Skladiste', '0028_cijev_cijevhistory'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cijevhistory',
            old_name='Promjer',
            new_name='promjer',
        ),
        migrations.AlterField(
            model_name='alat',
            name='inv_broj',
            field=models.PositiveIntegerField(default=0, verbose_name='Inventurni broj, blank=True, null=True'),
        ),
        migrations.AlterField(
            model_name='alat',
            name='naziv',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Naziv'),
        ),
        migrations.AlterField(
            model_name='alat',
            name='proizvodjac',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Proizvođač'),
        ),
        migrations.AlterField(
            model_name='alat',
            name='sr_broj',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Serijski broj'),
        ),
        migrations.AlterField(
            model_name='alat',
            name='zaduzio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Zaduži na'),
        ),
        migrations.AlterField(
            model_name='materijal',
            name='inv_broj',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Inventurni broj'),
        ),
        migrations.AlterField(
            model_name='materijal',
            name='izdana_kolicina',
            field=models.IntegerField(blank=True, null=True, verbose_name='Izdana količina'),
        ),
        migrations.AlterField(
            model_name='materijal',
            name='izdano_na',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Izdaj na'),
        ),
        migrations.AlterField(
            model_name='materijal',
            name='kolicina',
            field=models.IntegerField(blank=True, null=True, verbose_name='Količina'),
        ),
        migrations.AlterField(
            model_name='materijal',
            name='naziv',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Naziv'),
        ),
        migrations.AlterField(
            model_name='materijal',
            name='radnja',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Radnja'),
        ),
        migrations.AlterField(
            model_name='materijal',
            name='zaprimio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users', to=settings.AUTH_USER_MODEL, verbose_name='Zaprimio'),
        ),
        migrations.AlterField(
            model_name='materijal',
            name='zaprimljena_kolicina',
            field=models.IntegerField(blank=True, null=True, verbose_name='Zaprimljena količina'),
        ),
        migrations.CreateModel(
            name='Zaduzenja',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inv_broj', models.PositiveIntegerField(default=0, verbose_name='Inventurni broj, blank=True, null=True')),
                ('naziv', models.CharField(blank=True, max_length=50, null=True, verbose_name='Naziv')),
                ('proizvodjac', models.CharField(blank=True, max_length=50, null=True, verbose_name='Proizvođač')),
                ('sr_broj', models.CharField(blank=True, max_length=50, null=True, verbose_name='Serijski broj')),
                ('kreirao', models.CharField(blank=True, max_length=50, null=True)),
                ('datum_zaduzivanja', models.DateField(auto_now=True, verbose_name='Zaduženo dana')),
                ('zadnje_osvjezeno', models.DateField(auto_now=True, verbose_name='Posljednje ažuriranje')),
                ('export_to_CSV', models.BooleanField(default=False)),
                ('zaduzio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Zaduži na')),
            ],
        ),
        migrations.CreateModel(
            name='MaterijalHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inv_broj', models.IntegerField(blank=True, default=0, null=True, verbose_name='Inventurni broj')),
                ('naziv', models.CharField(blank=True, max_length=50, null=True, verbose_name='Naziv')),
                ('kolicina', models.IntegerField(blank=True, null=True, verbose_name='Količina')),
                ('zaprimljena_kolicina', models.IntegerField(blank=True, null=True, verbose_name='Zaprimljena količina')),
                ('izdana_kolicina', models.IntegerField(blank=True, null=True, verbose_name='Izdana količina')),
                ('izdao', models.CharField(blank=True, max_length=50, null=True)),
                ('radnja', models.CharField(blank=True, max_length=50, null=True, verbose_name='Radnja')),
                ('reorder_level', models.IntegerField(blank=True, default=0, null=True)),
                ('export_to_CSV', models.BooleanField(default=False)),
                ('izdano_na', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Izdaj na')),
                ('zaprimio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='zaprimioh', to=settings.AUTH_USER_MODEL, verbose_name='Zaprimio')),
            ],
        ),
    ]
