# Generated by Django 3.1.5 on 2021-02-25 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Skladiste', '0029_auto_20210224_2245'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='materijal',
            name='zaprimio',
        ),
        migrations.RemoveField(
            model_name='materijal',
            name='zaprimljena_kolicina',
        ),
        migrations.RemoveField(
            model_name='materijalhistory',
            name='zaprimio',
        ),
        migrations.RemoveField(
            model_name='materijalhistory',
            name='zaprimljena_kolicina',
        ),
        migrations.AddField(
            model_name='materijal',
            name='vlasnik',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='materijalhistory',
            name='vlasnik',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
