# Generated by Django 3.1.5 on 2021-02-25 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Skladiste', '0030_auto_20210225_0611'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='materijalhistory',
            name='reorder_level',
        ),
        migrations.AddField(
            model_name='materijal',
            name='zadnje_osvjezeno',
            field=models.DateField(auto_now=True, verbose_name='Posljednje ažuriranje'),
        ),
        migrations.AddField(
            model_name='materijalhistory',
            name='zadnje_osvjezeno',
            field=models.DateField(auto_now=True, verbose_name='Posljednje ažuriranje'),
        ),
    ]
