# Generated by Django 3.1.5 on 2021-01-14 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Automobil',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marka', models.CharField(max_length=50)),
                ('ime', models.CharField(max_length=50)),
                ('tablica', models.CharField(max_length=20)),
                ('registracija', models.DateField(null=True)),
                ('servis', models.DateField(null=True)),
                ('servis_kilometri', models.PositiveIntegerField(null=True)),
            ],
        ),
    ]
