# Generated by Django 3.1.5 on 2021-03-07 20:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Automobil',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ime', models.CharField(max_length=50, verbose_name='Model')),
                ('marka', models.CharField(max_length=50)),
                ('tablica', models.CharField(max_length=20)),
                ('pocetna_kilometraza', models.IntegerField(default=0)),
                ('zavrsna_kilometraza', models.IntegerField(verbose_name='Kilometri')),
                ('registracija', models.DateField(null=True, verbose_name='Tehnički')),
                ('servis_kilometri', models.IntegerField(null=True, verbose_name='Servis na')),
            ],
        ),
        migrations.CreateModel(
            name='Kilometraza',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datum', models.DateField(auto_now=True)),
                ('pocetna', models.IntegerField(blank=True, null=True)),
                ('zavrsna', models.IntegerField(blank=True, null=True)),
                ('relacija', models.CharField(blank=True, max_length=256, null=True)),
                ('automobil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auti_app.automobil')),
            ],
        ),
    ]
