# Generated by Django 3.1.5 on 2021-03-15 21:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('auti_app', '0002_auto_20210314_2336'),
    ]

    operations = [
        migrations.AddField(
            model_name='automobil',
            name='atest',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Atest vatrogasnog aparata'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='kilometraza',
            name='dnevna_kilometraza',
            field=models.IntegerField(blank=True, default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='kilometraza',
            name='datum',
            field=models.DateField(auto_now_add=True),
        ),
    ]
