# Generated by Django 3.1.5 on 2021-03-23 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auti_app', '0003_auto_20210315_2215'),
    ]

    operations = [
        migrations.AddField(
            model_name='automobil',
            name='do_servisa',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='automobil',
            name='atest',
            field=models.DateField(blank=True, verbose_name='Atest vatrogasnog aparata'),
        ),
    ]
