# Generated by Django 3.1.5 on 2021-03-23 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auti_app', '0004_auto_20210323_1729'),
    ]

    operations = [
        migrations.AlterField(
            model_name='automobil',
            name='do_servisa',
            field=models.IntegerField(blank=True),
        ),
    ]
